"""Add current_step to leads and create lead_answers table

Revision ID: eef03f799c01
Revises: 32e8eb19a3ad
Create Date: 2026-01-14 11:41:25.495499

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eef03f799c01"
down_revision: str | Sequence[str] | None = "32e8eb19a3ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lead_answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=False),
        sa.Column("question_key", sa.String(length=64), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lead_answers_lead_id"), "lead_answers", ["lead_id"], unique=False)
    op.create_index(
        op.f("ix_lead_answers_question_key"), "lead_answers", ["question_key"], unique=False
    )

    # Add current_step column as nullable first
    op.add_column("leads", sa.Column("current_step", sa.Integer(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE leads SET current_step = 0 WHERE current_step IS NULL")
    # Now make it NOT NULL
    op.alter_column("leads", "current_step", nullable=False, server_default="0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("leads", "current_step")
    op.drop_index(op.f("ix_lead_answers_question_key"), table_name="lead_answers")
    op.drop_index(op.f("ix_lead_answers_lead_id"), table_name="lead_answers")
    op.drop_table("lead_answers")
    # ### end Alembic commands ###
